import dotenv from "dotenv";
import { Handler } from "@netlify/functions";
import { GoogleSpreadsheet } from "google-spreadsheet";

dotenv.config();

const doc = new GoogleSpreadsheet(
  `11UJGryQoaei5zAoZPtgwifuvTJp5Sj-7nUSjaXLlnVo`
);

const handler: Handler = async (event) => {
  console.log(process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL);
  console.log(process.env.GOOGLE_PRIVATE_KEY);
  // do not allow GET requests
  if (event.httpMethod !== "GET") {
    return {
      statusCode: 400,
      body: JSON.stringify({ error: "invalid http method, expected 'POST'" }),
    };
  }

  console.log("huzzah");

  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    private_key: process.env.GOOGLE_PRIVATE_KEY,
  });

  console.log("service account loaded");
  console.log("(*)");
  console.log("(*)");
  console.log("(*)");

  await doc.loadInfo(); // loads document properties and worksheets
  console.log(doc.title);
};

export { handler };
